project_name: goreg

release:
  github:
    owner: magicdrive
    name: goreg
  draft: false
  prerelease: "false"

builds:
  - id: goreg
    goos:
      - linux
      - darwin
      - windows
    ignore:
      - goos: darwin
        goarch: "386"
    ldflags:
      - -s -w -X "main.version=v{{.Version}}"
    env:
      - CGO_ENABLED=0
    binary: goreg
    main: ./main.go

archives:
  - id: tar.gz
    format: tar.gz
    files:
     - src: misc/completions/goreg-completion.sh
       dst: completions/goreg-completion.sh
     - src: misc/completions/zsh/_goreg
       dst: completions/zsh/_goreg
     - src: misc/completions/bash/goreg-completion.bash
       dst: completions/bash/goreg-completion.bash

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

brews:
  - name: goreg
    repository:
      owner: magicdrive
      name: homebrew-tap
      branch: main
    homepage: "https://github.com/magicdrive/goreg"
    description: "Yet another alternate `goimports` tool."
    license: "MIT"
    ids: [tar.gz]
    install: |
      bin.install "goreg"
    extra_install: |
      bash_completion.install "completions/bash/goreg-completion.bash" => "goreg"
      zsh_completion.install "completions/zsh/_goreg" => "_goreg"
    test: |
      system "#{bin}/goreg", "--version"
    commit_author:
      name: magicdrive bot
      email: hiroshi.ikegami+githubbot@magicdrive.jp

